version: '3.7'
services:
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    expose:
      - "6379"

  msc-loteria-api-local:
    build: $GO_BITBUCKET_PATH/loteria-api/.
    restart: always
    ports:
      - "8081:8081"
    expose:
      - "8081"
    env_file:
      - $DEVPATH/envs/loteria-api.env
    container_name: loteria-api
    depends_on:
      - redis